//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastBlogProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public Authors()
        {
            this.Articles = new HashSet<Articles>();
            this.Comments = new HashSet<Comments>();
            this.Pages = new HashSet<Pages>();
        }
    
        public int AuthorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Bio { get; set; }
        public string UserName { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        public enum _Role
        {
            Admin = 1,

            User = 2
        }
    
        public virtual ICollection<Articles> Articles { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Pages> Pages { get; set; }
    }
}
