//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastBlogProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int PageID { get; set; }
        public string Title { get; set; }
        public string PageContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AuthorId { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
